from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum


class DocumentType(str, Enum):
    """Supported document types"""
    PDF = "pdf"
    DOCX = "docx"
    TXT = "txt"
    CSV = "csv"
    XLSX = "xlsx"


class DocumentMetadata(BaseModel):
    """Document metadata"""
    filename: str
    document_type: DocumentType
    upload_timestamp: datetime = Field(default_factory=datetime.now)
    file_size: int
    num_chunks: int = 0
    document_id: str


class QueryRequest(BaseModel):
    """User query request"""
    query: str
    conversation_id: Optional[str] = None
    clarifications: Optional[Dict[str, str]] = None


class ClarificationQuestion(BaseModel):
    """A clarifying question generated by ClaRA"""
    question_id: str
    question_text: str
    suggested_options: Optional[List[str]] = None
    question_type: str = "open"  # open, multiple_choice


class ClarificationResponse(BaseModel):
    """Response containing clarifying questions"""
    conversation_id: str
    needs_clarification: bool
    questions: List[ClarificationQuestion]
    reasoning: Optional[str] = None


class DocumentChunk(BaseModel):
    """A chunk of document with metadata"""
    chunk_id: str
    document_id: str
    content: str
    chunk_index: int
    metadata: Dict[str, Any]


class RetrievedDocument(BaseModel):
    """Retrieved document chunk with relevance score"""
    chunk: DocumentChunk
    relevance_score: float
    reasoning: Optional[str] = None


class AnswerResponse(BaseModel):
    """Final answer response"""
    conversation_id: str
    answer: str
    sources: List[RetrievedDocument]
    confidence_score: float
    used_clarifications: bool = False


class UploadResponse(BaseModel):
    """Document upload response"""
    success: bool
    message: str
    document_metadata: Optional[DocumentMetadata] = None


class HealthResponse(BaseModel):
    """Health check response"""
    status: str
    timestamp: datetime = Field(default_factory=datetime.now)
    version: str = "1.0.0"
